### ISSUE TITLE
Lack of comprehensiveness in translation

### ISSUE THREAD

**Issue by Xrhhhilo** [xicri/genshin-langdata#183]
Suggest grabbing it from https://genshin-impact.fandom.com/
There's a section called "other language".

**Comment by xicri** [comment]
@Xrhhhilo Hi, thanks for your suggestion, and sorry for the delayed reply.

Unfortunately, I don't want to refer to Genshin Impact Wiki on Fandom as a data source.

1. Compliance issue: Genshin Impact Wiki is rumored to depend on GenshinData as a data source. Since [GenshinData is banned by miHoYo](https://github.com/github/dmca/blob/master/2021/05/2021-05-18-genshin-impact.md), there are high legal risks to use data derived from it.
2. Reliability issue: Genshin Impact Wiki is made by the community, and it is not the primary source. I prefer referring to official sources such as the game itself, official movies uploaded to YouTube and Bilibili, and information posted on social media.

Instead, I'm considering scraping [HoYoWiki](https://wiki.hoyolab.com) to import data to Genshin Dictionary's dataset.
