### ISSUE TITLE
Add new keywords for Ver.4.6 genshin-langdata

### ISSUE THREAD

**Issue by yasuking0304** [xicri/genshin-langdata#193]
I want you to add new keywords for Ver.4.6.

So, basically, I referred to here and picked up the missing basic keywords

https://genshin-impact.fandom.com/wiki

Charactor of Fonraine

| English | Japanese | Chinese Simplifed | Note(ja) | Type |
|---|---|---|---|---|
|Arlecchino|アレルッキーノ|阿蕾奇诺|| Playable |
|Peruere|ペルヴェーレ|佩露薇利|アレルッキーノの幼名| NPC |
|Crucabena|クルセビナ|库嘉维娜|| NPC |
|Clervie|クリーヴ|克雷薇|| NPC |
|Osse|ウッスー|小呜斯|「ウラノポリスのウラニデス」の略称|NPC|
|Boethius|ボエティウス|波爱修斯||NPC|
|Scylla|スキュラ|斯库拉||NPC|
|Cassiodo|カッシオドル|卡西奥多||NPC|

Charactor of Sumeru
| English | Japanese | Chinese Simplifed | Note(ja) | Type |
|---|---|---|---|---|
|Sethos|セトス|赛索斯||Playable?|

Region of Fontaine
| English | Japanese | Chinese Simplifed | Note(ja) |
|---|---|---|---|
|Nostoi Region|ノストイ地区|诺思托伊区||
|Faded Castle|色褪せた城|褪色古堡||
|Petrichor|ペトリコール町|佩特莉可||
|Sea of Bygone Eras|往日の海|旧日之海||
|Initinum Iani|ヤヌスの門|雅努斯之门||
|Hortus Euergetis|ホルトゥス・ユーゲレティス|优恩花园||
|Alta Semita|アルタ・セミタ|崇高大道|
|Clivus Capitolinus|アピトリヌス山|卡皮托林山|
|Collegium Phonascorum|諧律院|谐律院|

Region of Sumeru
| English | Japanese | Chinese Simplifed | Note(ja) |
|---|---|---|---|
|Bayda Harbor|バイダ港|拜达港||

Weapon
| English | Japanese | Chinese Simplifed | Note(ja) |
|---|---|---|---|
|Crimson Moon's Semblance|赤月のシルエット|赤月之形||

Enemy
| English | Japanese | Chinese Simplifed | Note(ja) |
|---|---|---|---|
|Praetorian Golem|魔像プラエトリアニ|魔像禁卫||

BOSS
| English | Japanese | Chinese Simplifed | Note(ja) |
|---|---|---|---|
|Statue of Marble and Brass|白石と黄銅の彫像|白石与黄铜的造像|魔像レガトゥス|

Item
| English | Japanese | Chinese Simplifed | Note(ja) |
|---|---|---|---|
|Fragment of a Golden Melody|金色の旋律の断章|金色旋律的断章||

**Comment by xicri** [comment]
Thanks, please create PR. Since it is a bit hard to add review comment on Issue, I will review after you create the PR.

From next time, can you avoid using Genshin Impact Wiki on Fandom as a data source?
I hear some information on the Genshin Impact Wiki is extracted from GenshinData, the game dataset which are illegally extracted from Genshin Impact.

I think miHoYo/HoYoverse tolerates some kinds of violation of their legal rights such as copyright of their artworks. I don't think we should always be strict if the creators implicitly allow us.
However,  because [HoYoverse has banned GenshinData from GitHub](https://www.gamerbraves.com/genshin-impact-repository-genshindata-gets-dmca-takedown-despite-not-hosting-leak-content/), I don't think they kindly allow us to upload the extracted dataset of the game.

Since the Genshin Dictionary can exist thanks to the Genshin Impact itself and its creators at HoYoverse, I want to be respectful for them and their rights.
