### ISSUE TITLE
Add new keywords for Ver.4.7 prequel genshin-langdata

### ISSUE THREAD

**Issue by yasuking0304** [xicri/genshin-langdata#218]
Since we have advanced the story of the first half of Ver 4.7, we will add keywords. This time, I am creating it from Genshin Impact's "Archive" - "Travel Log". Also, I'm sorry, but I'm including typo and those that were found to be misread.

Charactor of Fonraine

| English | Japanese | Chinese Simplifed | Note(ja) | Type | memo|
|---|---|---|---|---|---|
|Emilie|エミリエ|艾梅莉埃|| Playable |Ver4.8で実装?|
|Florian|フロリアン|弗洛莱恩|| NPC ||

Charactor of Sumeru

| English | Japanese | Chinese Simplifed | Note(ja) | Type | memo |
|---|---|---|---|---|---|
|Atossa|アトッサ|阿托莎|魔神任務 第4章第6幕「ベッドタイムストーリー」などに登場するキャラクター| NPC ||
|Bahram|バハラーム|巴兰|| NPC |登場自体はVer.3.0 スメール編から|
|Amadhiah|アマディア|阿玛兹亚|| NPC |登場自体はVer.3.0 スメール編から|
|Caribert Alberich|カリベルト・アルベリヒ|卡利贝尔·亚尔伯里奇|魔神任務 第4章第6幕「ベッドタイムストーリー」などに登場するキャラクター| NPC |厳密にはカリベルトはコロタールの私生児であるためアルベリヒ姓ではないが「ベッドタイムストーリー」「世界規模の語り」の中で青年として具現化した姿に旅人はカリベルト・アルベリヒと呼びかけている tags:[Khaenri'ah]|
|-|コロタール・アルベリヒ||| NPC |入力済み tags:[Khaenri'ah]|

Charactor of Khaenri'ah

| English | Japanese | Chinese Simplifed | Note(ja) | Type | memo|
|---|---|---|---|---|---|
|Hroptatyr|フロプタチュール|海洛塔帝|[賢者]の通称を持つ。[カーンルイアの五大罪人]のひとり| NPC |
|Vedrfolnir|ヴェズルフェルニル|维瑟弗尼尔|[予言者]の通称を持つ。[カーンルイアの五大罪人]のひとり| NPC |ダインスレイヴの兄|
|-|レインドット||[黄金]の通称を持つ。[カーンルイアの五大罪人]のひとり|NPC |入力済み tags:[Khaenri'ah]|
|Surtalogi|スルトロッチ|苏尔特洛奇|[極悪騎]の通称を持つ。[カーンルイアの五大罪人]のひとり|NPC ||
|Rerir|レリル|雷利尔|[月の狩人]の通称を持つ。[カーンルイアの五大罪人]のひとり|NPC ||
|The Wise|賢者(けんじゃ)|贤者|[フロプタチュール]の通称。[カーンルイアの五大罪人]のひとり| NPC |
|The Visionary|予言者(よげんしゃ)|预言家|[ヴェズルフェルニル]の通称。[カーンルイアの五大罪人]のひとり| NPC |ダインスレイヴの兄|
|Gold|黄金(おうごん)|黄金|[レインドット]の通称。[カーンルイアの五大罪人]のひとり|NPC ||
|The Foul|極悪騎(ごくあくき)|极恶骑|[スルトロッチ]の通称。[カーンルイアの五大罪人]のひとり|NPC ||
|Rächer of Solnari|月の狩人(つきのかりゅうど)|猎月人|[レリル]の通称。[カーンルイアの五大罪人]のひとり|NPC |「ä」はアルファベット文字ではないウムラウトつき。ウムラウトなしで入力するべきかも|
|The Five Sinners of Khaenri'ah|カーンルイアの「五大罪人」(カーンルイアのごだいつみびと)|坎瑞亚的「五大罪人」|カーンルイアを裏切った5人の[罪人]の通称|NPC ||

Weapon
| English | Japanese | Chinese Simplifed | Note(ja) | type | memo |
|---|---|---|---|---|---|
|Absolution|赦罪(しゃざい)|赦罪|| Sword |
|Cloudforged|築雲(ちくうん)|筑云|v4.7 期間限定イベント「堅守演習」報酬| Bow |
|| 白雨心弦| || Bow | Not yet |

Domain
| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
||幻想シアター||| Not yet |

Location
| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|The Wingalet|ウィンガレット号|维恩歌莱号|| メロピデ要塞で建造された飛行艦船 tag:[Facility, Organization, Fontaine] |

Event

| English | Japanese | Chinese Simplifed | Note(ja) | memo |
|---|---|---|---|---|
|Mutual Security Enhancing Simulation|堅守演習|安固诸方之述演|Ver.4.7限定イベント||

**Comment by xicri** [comment]
Thanks as always, Kaneko-san.
Looks good!

Here are some minor review comments:

- Caribert Alberich ― "Caribert" is [already registered](https://genshin-dictionary.com/ja/caribert), but this word also means the chapter name of an Archon Quest and we cannot add his surname Alberich to this word. Let's add "Caribert Alberich" in addition to "Caribert".
- Bahram and Amadhiah ― I think they are worth adding because I think they played an important role in the last Archon Quest, and they also appeared in another large-scale World Quest Aranyaka (ja: 森林書, the series of the Aranara's World Quests)
- Rächer of Solnari ― As a principle, I keep the diacritical marks such as Umlaut to respect the expressions by the translators at HoYoverse. If there is no additional concerns, let's keep "Rächer" rather than "Racher".
- Typos: if you include these words in the notes, please correct them. (Were you sleepy or drunk? 😎)
    - ウラムト (◯ ウムラウト)
    - ダインスレイブ (◯ ダインスレイヴ)
    - ペロピデ要塞 (◯ メロピデ要塞)
    - Fonraine (◯ Fontaine)

**Comment by yasuking0304** [comment]
Oops. I've fixed the error in the issue.
I've been having a cold lately, so I'll put out a PR this weekend.
